# Generated by Django 2.1.5 on 2019-01-16 10:39

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='upload_img/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Изображение ',
                'verbose_name_plural': 'Изображения ',
            },
        ),
        migrations.CreateModel(
            name='ImageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название сервиса')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='upload_img/', verbose_name='Изображение сервиса для главной')),
                ('head_image', models.ImageField(upload_to='upload_img/', verbose_name='Изображение сервиса для страницы')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Иконка')),
                ('short_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание ')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Полное описание ')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.ImageTag', verbose_name='Тэг'),
        ),
    ]
