# Generated by Django 2.1.5 on 2019-01-17 10:39

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190116_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1, verbose_name='Порядок отображения')),
                ('image', models.ImageField(upload_to='upload_img/', verbose_name='Изображение для банера')),
                ('small_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Маленький текст')),
                ('big_text', models.CharField(max_length=255, null=True, verbose_name='Большой текст')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Название поста')),
                ('name_slug', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='upload_img/', verbose_name='Изображение для страницы')),
                ('head_image', models.ImageField(upload_to='upload_img/', verbose_name='Изображение  для шапки страницы')),
                ('full_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Полное описание ')),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='head_image',
            field=models.ImageField(upload_to='upload_img/', verbose_name='Изображение сервиса для шапки страницы'),
        ),
        migrations.AddField(
            model_name='banner',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.Post', verbose_name='Относится к посту'),
        ),
    ]
