# Generated by Django 2.1.5 on 2019-01-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190117_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Короткое описание в шапке страницв '),
        ),
    ]
