# Generated by Django 2.1.5 on 2019-01-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_post_head_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_main_service',
            field=models.BooleanField(default=True, verbose_name='Основной сервис?'),
        ),
    ]
