# Generated by Django 2.1.5 on 2019-01-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_service_is_main_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга ', 'verbose_name_plural': 'Услуги '},
        ),
        migrations.AddField(
            model_name='service',
            name='head_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Короткое описание в шапке страницв '),
        ),
    ]
