# Generated by Django 2.1.5 on 2019-01-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20190117_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='show_at_home',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной?'),
        ),
    ]
