# Generated by Django 2.1.5 on 2019-01-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_service_show_at_home'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='image',
            name='big_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Большой текст'),
        ),
        migrations.AddField(
            model_name='image',
            name='small_text',
            field=models.CharField(max_length=255, null=True, verbose_name='Малый текст'),
        ),
        migrations.DeleteModel(
            name='ImageTag',
        ),
    ]
